version: "3.9"
services:
  backend:
    container_name: aboba_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./test.db:/app/test.db